version: '3.8'

services:
  dona-nice-app:
    build:
      context: https://github.com/mathewsfs/projeto-dn-app.git
      dockerfile: backend/Dockerfile
    container_name: dona-nice-app
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=https://donanice.fluxora.space
      - JWT_SECRET=dona-nice-jwt-secret-production-2024-256bits-secure-key
      - APP_DOMAIN=donanice.fluxora.space
      - TRAEFIK_ACME_EMAIL=mathewsfs@hotmail.com
    volumes:
      - dona-nice-data:/app/data
      - dona-nice-logs:/var/log
    restart: unless-stopped

volumes:
  dona-nice-data:
    driver: local
  dona-nice-logs:
    driver: local
